<div class="header-top-desktop-left">
    <?php
    echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('header-top-contact-phone')
            ->toHtml();
    ?>
</div>

<div class="header-top-desktop-center">
    <?php
    echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('header-top-center-links')
            ->toHtml();
    ?>
</div>

<div class="header-top-mobile-left">
    <?php
    echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('header-top-address-mobile')
            ->toHtml();
    ?>
</div>


<div class="header-top-mobile-right">
    <?php
    echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('header-contact-phone-mobile')
            ->toHtml();
    ?>
</div>



