<div class="footer-middle-item">
    <?php
    echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer-middle-1')
            ->toHtml();
    ?>
</div>
<div class="footer-middle-item">
    <?php
    echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer-middle-2')
            ->toHtml();
    ?>
</div>
<div class="footer-middle-item">
    <?php
    echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer-middle-3')
            ->toHtml();
    ?>
</div>

